package client_grpc

import(
	"github.com/iancoleman/strcase"
	"github.com/thecodedproject/msgen/generator/files"
	"github.com/thecodedproject/msgen/parser"
	"io"
)

type Method struct {
	Name string
	Args []parser.Field
	ReturnTypes []string
}

func GenerateClient(
	i parser.ProtoInterface,
	outputDir string,
) error {

	panic("not implemented")
	return nil
}

func GenerateBuffer(
	serviceRootImportPath string,
	i parser.ProtoInterface,
	writer io.Writer,
) error {

	baseTemplate := files.BaseTemplate()

	header, err := baseTemplate.Parse(grpcHeaderTmpl)
	if err != nil {
		return err
	}

	err = header.Execute(writer, struct{
		Package string
		Imports []string
		ServiceName string
	}{
		Package: "grpc",
		Imports: []string{
			"context",
			"flag",
			"google.golang.org/grpc",
			"google.golang.org/grpc/connectivity",
			serviceRootImportPath + "/proto",
			"testing",
		},
		ServiceName: "SomeService",
	})
	if err != nil {
		return err
	}


	for _, method := range i.Methods {

		methodParams := Method{
			Name: method.Name,
		}

		for _, mess := range i.Messages {
			if mess.Name == method.RequestMessage {
				methodParams.Args = mess.Fields
			} else if mess.Name == method.ResponseMessage {
				for _, f := range mess.Fields {
					methodParams.ReturnTypes = append(methodParams.ReturnTypes, f.Type)
				}
			}
		}

		for i := range methodParams.Args {
			methodParams.Args[i].Name = strcase.ToLowerCamel(
				methodParams.Args[i].Name,
			)
		}

		if len(methodParams.ReturnTypes) == 0 {

			methodEmptyReturnTemplate, err := baseTemplate.Parse(grpcMethodEmptyReturnTmpl)
			if err != nil {
				return err
			}

			err = methodEmptyReturnTemplate.Execute(writer, methodParams)
			if err != nil {
				return err
			}

		} else {

			methodParams.ReturnTypes = append(methodParams.ReturnTypes, "error")

			methodTemplate, err := baseTemplate.Parse(grpcMethodTmpl)
			if err != nil {
				return err
			}

			err = methodTemplate.Execute(writer, methodParams)
			if err != nil {
				return err
			}
		}
	}

	return nil
}

var grpcHeaderTmpl = `package {{.Package}}

// Generated by msgen. DO NOT EDIT.

import(
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

var address = flag.String("{{ToLower .ServiceName}}_grpc_address", "", "host:port of {{ToLower .ServiceName}} gRPC service")

type client struct {
	rpcConn *grpc.ClientConn
	rpcClient addpb.AddClient
}

func IsGRPCEnabled() bool {
	return *address != ""
}

func New() (*client, error) {
	conn, err := grpc.Dial(*address, grpc.WithInsecure())
	if err != nil {
		return nil, err
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	for {
		if conn.GetState() == connectivity.Ready {
			break
		}
		if !conn.WaitForStateChange(ctx, conn.GetState()) {
			return nil, errors.New("grpc timeout whilst connecting")
		}
	}

	return &client{
		rpcConn: conn,
		rpcClient: proto.NewSomeServiceClient(conn),
	}, nil
}

func NewClientForTesting(t *testing.T, conn *grpc.ClientConn) *client {
	return &Client{
		rpcConn: conn,
		rpcClient: addpb.NewAddClient(conn),
	}
}

`

var grpcMethodTmpl = `func (c *client) {{.Name}}(
	ctx context.Context,
{{- range .Args}}
	{{.Name}} {{.Type}},
{{- end}}
) {{FuncRetVals .ReturnTypes}} {

	res, err := c.rpcClient.{{.Name}}(
		ctx,
		&proto.{{.Name}}Request{
{{- range .Args}}
			{{.Name}}: {{.Name}},
{{- end}}
		},
	)
	if err != nil {
		return int64{}, string{}, err
	}

	return res.int64Value, res.stringValue, nil
}

`

var grpcMethodEmptyReturnTmpl = `func (c *client) {{.Name}}(
	ctx context.Context,
{{- range .Args}}
	{{.Name}} {{.Type}},
{{- end}}
) error {

	_, err := c.rpcClient.{{.Name}}(
		ctx,
		&proto.{{.Name}}Request{
{{- range .Args}}
			{{ToCamel .Name}}: {{.Name}},
{{- end}}
		},
	)
	return err
}

`
