package types

import(
	"github.com/thecodedproject/msgen/generator/files/common"
	"github.com/thecodedproject/msgen/parser"
	"github.com/thecodedproject/msgen/parser/proto_helpers"
	"io"
	"path"
)

const(
	relativePath = "types.go"
)

type Method struct {
	Name string
	Args []parser.Field
	ReturnArgs []parser.Field
}

func Generate(
	serviceRootImportPath string,
	i parser.ProtoInterface,
	outputDir string,
) error {

	n := proto_helpers.NestedMessages(i)
	if len(n) == 0 {
		return nil
	}

	outputFile := path.Join(outputDir, relativePath)

	writer, err := common.CreatePathAndOpen(outputFile)
	if err != nil {
		return err
	}

	return GenerateBuffer(
		serviceRootImportPath,
		i,
		writer,
	)
}

func GenerateBuffer(
	serviceRootImportPath string,
	i parser.ProtoInterface,
	writer io.Writer,
) error {

	serviceName := common.ServiceNameFromRootImportPath(serviceRootImportPath)

	baseTemplate := common.BaseTemplate(serviceName)

	header, err := baseTemplate.Parse(tmpl)
	if err != nil {
		return err
	}

	err = header.Execute(writer, struct{
		Package string
		Imports []string
		NestedTypes []parser.Message
	}{
		Package: serviceName,
		NestedTypes: proto_helpers.NestedMessages(i),
	})
	if err != nil {
		return err
	}

	return nil
}


var tmpl = `package {{.Package}}

// Generated by msgen. DO NOT EDIT.

import(
{{- range .Imports}}
	{{.}}
{{- end}}
)

{{- range .NestedTypes}}

type {{.Name}} struct {
{{- range .Fields}}
	{{ToCamel .Name}} {{.Type}}
{{- end}}
}
{{- end}}

`

